services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blemapping
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/blemapping?schema=public"
      JWT_SECRET: "your_jwt_secret_key_here"
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

  frontend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: